SECRET_KEY = b'\xe9\xbc\xcc\x1d\xba\xb0\xa3\xb9\xd6\xb5\x87\x8d'
SQLALCHEMY_DATABASE_URI = 'sqlite:///userbooks.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
CSRF_TOKEN = True
MAIL_SERVER ='smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = your_email
MAIL_PASSWORD = your_email_password
POST_PER_PAGE = 30
